spring:
  application:
    name: pay-admin-api

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/pay_admin}
    username: ${DB_USER:pay_admin}
    password: ${DB_PASSWORD:pay_admin}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: ${DB_SCHEMA:pay_admin}
        jdbc.time_zone: UTC
        format_sql: false

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    schemas: ${DB_SCHEMA:pay_admin}
    default-schema: ${DB_SCHEMA:pay_admin}
    create-schemas: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER:http://localhost:8080/realms/pay-admin}

server:
  port: ${SERVER_PORT:8081}
  forward-headers-strategy: framework

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized

logging:
  level:
    org.springframework.security: INFO
    ru.copperside.admin: DEBUG
